//----------------------------------------------------------------------------------
//! DIAGErosionDilate module definitions.
/*!
// \file    ErosionDilate.script
// \author  Luc Nies
// \date    2016-03-04
*/
//----------------------------------------------------------------------------------


Window {
  Vertical {
    margin = 3
    Field radius {
      tooltip = ""
    }
	CheckBox erosion {title = "Erosion, not dilation"}
	Button apply {title = "Apply"} 
  }
}